name: main

on:
  push:
    branches: [ master ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ master ]

jobs:
  test:
    env:
      QT_QPA_PLATFORM: offscreen
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -e .[tests]

      - name: Run tests
        run: pytest tests --cov=./ --cov-report=xml -s

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          env_vars: OS, PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true

  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Setup deploy
        run: |
          pip install --upgrade setuptools wheel twine
          python setup.py sdist bdist_wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true

      - name: Github Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_COMPRESS: xz
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  winbuild:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: deploy
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.9' ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -e .[dev]

      - name: pyinstaller
        run: |
          pyinstaller --noconfirm --clean tsuchinoko.spec

      - name: Github Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_COMPRESS: xz
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Capture tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Create installer
        uses: joncloud/makensis-action@v4
        with:
          arguments: "/V3 /DVERSION=${{steps.vars.outputs.tag}}"
